/// <reference types="node" />
import { Hono } from "hono";
import { describe,expect,it } from "vitest";
import { observationCapabilityValues,operationKindSchema,workspaceCapabilityValues } from "@gardener/contracts";
import { createAgentSource } from "@gardener/core";
import { agentManagement } from "../src/agent-management";
import type { AuthorizationVariables } from "../src/authorization";
import type { Env } from "../src/env";
import { migration,newAgentDatabase } from "./persistence-test-db";

function setup(){const {sqlite,db}=newAgentDatabase();sqlite.exec(`
  INSERT INTO users(id,display_name)VALUES('owner','Owner Name'),('member','Member Name');
  INSERT INTO external_identities(id,user_id,provider,provider_subject,username)VALUES('oi','owner','github','1','owner'),('mi','member','github','2','member');
  INSERT INTO memberships(id,user_id,role,permanent)VALUES('om','owner','owner',1),('mm','member','member',0);
  INSERT INTO repositories(id,installation_id,owner,name,default_branch,active)VALUES('10','20','acme','widgets','main',1),('11','20','acme','tools','main',1);
  INSERT INTO agents(id,slug,name,created_by)VALUES('agent-one','one','Agent One','owner');`);
  const env={DB:db,LOCAL_DEV_BYPASS:"false"} as Env;
  const app=new Hono<{Bindings:Env;Variables:AuthorizationVariables}>();app.use("/api/*",async(c,next)=>{const mode=c.req.header("x-principal")??"owner";const member=mode==="member";c.set("authorization",{userId:member?"member":"owner",role:member?"member":"owner",displayName:member?"Member Name":"Owner Name",identity:{provider:"github",providerSubject:member?"2":"1",login:member?"member":"owner"},principalKind:mode==="mcp"?"mcp-token":"dashboard-session"});c.set("actor",member?"member":"owner");c.set("actorLogin",member?"Member Name":"Owner Name");await next()});app.route("/api",agentManagement);return{sqlite,env,app};}
const request=(method:string,body:unknown,principal="owner")=>({method,headers:{"content-type":"application/json","x-principal":principal},body:JSON.stringify(body)});
const overlapSource=createAgentSource(`---
schema: gardener.agent/v1
name: Comment agent
description: Propose issue comments.
triggers: [github.issue.opened]
capabilities:
  effects: [issue.comment.create]
authority-ceiling: automatic
---
Propose one relevant comment for review.`);
const counts=(sqlite:import("node:sqlite").DatabaseSync)=>sqlite.prepare(`SELECT
  (SELECT CAST(value AS INTEGER) FROM settings WHERE key='assignment_epoch') epoch,
  (SELECT COUNT(*) FROM agent_repository_assignment_history) history,
  (SELECT COUNT(*) FROM audit_records WHERE action='assignment.updated') audits`).get();

describe("W5A assignment and policy HTTP authority",()=>{
  it("uses human names, enforces the principal matrix, narrows in-place, and makes repeats no-ops",async()=>{const{sqlite,env,app}=setup();try{
    expect((await app.request("https://g.test/api/agents/agent-one/assignments",request("POST",{repositoryId:"10",authorityCeiling:"automatic",expectedAssignmentEpoch:1},"member"),env)).status).toBe(403);
    expect((await app.request("https://g.test/api/agents/agent-one/assignments",request("POST",{repositoryId:"10",authorityCeiling:"automatic",expectedAssignmentEpoch:1},"mcp"),env)).status).toBe(403);
    let response=await app.request("https://g.test/api/agents/agent-one/assignments",request("POST",{repositoryId:"10",authorityCeiling:"automatic",expectedAssignmentEpoch:1}),env);expect(response.status).toBe(201);
    let assignment=(await response.json() as any).assignments[0];expect(assignment).toMatchObject({agentDisplayName:"Agent One",repositoryDisplayName:"acme/widgets",enabled:false,version:1});
    response=await app.request(`https://g.test/api/assignments/${assignment.id}/enable`,request("POST",{expectedVersion:1,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:2},"member"),env);expect(response.status).toBe(403);
    response=await app.request(`https://g.test/api/assignments/${assignment.id}/enable`,request("POST",{expectedVersion:1,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:2}),env);assignment=(await response.json() as any).assignment;expect(assignment).toMatchObject({enabled:true,version:2});
    response=await app.request(`https://g.test/api/assignments/${assignment.id}/authority`,request("PUT",{authorityCeiling:"approval",expectedVersion:2,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:3},"member"),env);expect(response.status).toBe(200);assignment=(await response.json() as any).assignment;expect(assignment).toMatchObject({enabled:true,authorityCeiling:"approval",version:3});
    expect(sqlite.prepare("SELECT details_json FROM agent_repository_assignment_history WHERE assignment_version=3").get()).toEqual({details_json:'{"action":"authority_narrowed","from":"automatic","to":"approval"}'});
    const before=counts(sqlite);response=await app.request(`https://g.test/api/assignments/${assignment.id}/authority`,request("PUT",{authorityCeiling:"approval",expectedVersion:3,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:4},"member"),env);expect(await response.json()).toMatchObject({result:"noop"});expect(counts(sqlite)).toEqual(before);
    expect((await app.request(`https://g.test/api/assignments/${assignment.id}/authority`,request("PUT",{authorityCeiling:"automatic",expectedVersion:3,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:4},"member"),env)).status).toBe(403);
    expect((await app.request(`https://g.test/api/assignments/${assignment.id}/authority`,request("PUT",{authorityCeiling:"disabled",expectedVersion:3,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:4},"mcp"),env)).status).toBe(403);
    let snapshot=counts(sqlite);response=await app.request(`https://g.test/api/assignments/${assignment.id}/enable`,request("POST",{expectedVersion:3,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:4}),env);expect(await response.json()).toMatchObject({result:"noop"});expect(counts(sqlite)).toEqual(snapshot);
    response=await app.request(`https://g.test/api/assignments/${assignment.id}/disable`,request("POST",{expectedVersion:3,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:4},"member"),env);assignment=(await response.json() as any).assignment;snapshot=counts(sqlite);response=await app.request(`https://g.test/api/assignments/${assignment.id}/disable`,request("POST",{expectedVersion:4,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:5},"member"),env);expect(await response.json()).toMatchObject({result:"noop"});expect(counts(sqlite)).toEqual(snapshot);
    response=await app.request(`https://g.test/api/assignments/${assignment.id}/remove`,request("POST",{expectedVersion:4,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:5},"member"),env);assignment=(await response.json() as any).assignment;snapshot=counts(sqlite);response=await app.request(`https://g.test/api/assignments/${assignment.id}/remove`,request("POST",{expectedVersion:5,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:6},"member"),env);expect(await response.json()).toMatchObject({result:"noop"});expect(counts(sqlite)).toEqual(snapshot);
    response=await app.request(`https://g.test/api/assignments/${assignment.id}/re-add`,request("POST",{authorityCeiling:"approval",expectedVersion:5,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:6}),env);assignment=(await response.json() as any).assignment;snapshot=counts(sqlite);response=await app.request(`https://g.test/api/assignments/${assignment.id}/re-add`,request("POST",{authorityCeiling:"approval",expectedVersion:6,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:7}),env);expect(await response.json()).toMatchObject({result:"noop"});expect(counts(sqlite)).toEqual(snapshot);
  }finally{sqlite.close()}});
  it("rejects enable when its repository is inactive without consuming authority state",async()=>{const{sqlite,env,app}=setup();try{
    let response=await app.request("https://g.test/api/agents/agent-one/assignments",request("POST",{repositoryId:"10",authorityCeiling:"approval",expectedAssignmentEpoch:1}),env);const assignment=(await response.json() as any).assignments[0];sqlite.prepare("UPDATE repositories SET active=0 WHERE id='10'").run();const before=counts(sqlite);
    response=await app.request(`https://g.test/api/assignments/${assignment.id}/enable`,request("POST",{expectedVersion:1,expectedConfigHash:assignment.configHash,expectedAssignmentEpoch:2}),env);expect(response.status).toBe(409);expect(await response.json()).toMatchObject({error:"assignment_changed",assignmentEpoch:2});expect(counts(sqlite)).toEqual(before);expect(sqlite.prepare("SELECT enabled,version,config_hash FROM agent_repository_assignments WHERE id=?").get(assignment.id)).toEqual({enabled:0,version:1,config_hash:assignment.configHash});
  }finally{sqlite.close()}});
  it("materializes all-current atomically behind one aggregate overlap confirmation",async()=>{const{sqlite,env,app}=setup();try{
    async function publishActivate(agentId:string,epoch:number){let response=await app.request(`https://g.test/api/agents/${agentId}/drafts`,request("POST",{draftId:`draft-${agentId}`,source:overlapSource}),env);expect(response.status).toBe(201);response=await app.request(`https://g.test/api/agents/${agentId}/drafts/draft-${agentId}/publish`,request("POST",{}),env);const revision=(await response.json() as any).revision;response=await app.request(`https://g.test/api/agents/${agentId}/revisions/${revision.id}/activate`,request("POST",{expectedAssignmentEpoch:epoch,expectedCurrentRevisionId:null}),env);expect(response.status).toBe(200);return revision.id;}
    const firstRevision=await publishActivate("agent-one",1);let response=await app.request("https://g.test/api/agents",request("POST",{id:"agent-two",slug:"two",name:"Agent Two",description:"Second"}),env);expect(response.status).toBe(201);await publishActivate("agent-two",2);
    response=await app.request("https://g.test/api/agents/agent-two/assignments",request("POST",{repositoryId:"10",authorityCeiling:"automatic",expectedAssignmentEpoch:3}),env);let other=(await response.json() as any).assignments[0];response=await app.request(`https://g.test/api/assignments/${other.id}/enable`,request("POST",{expectedVersion:1,expectedConfigHash:other.configHash,expectedAssignmentEpoch:4}),env);expect(response.status).toBe(200);
    response=await app.request("https://g.test/api/agents/agent-one/assignments",request("POST",{allCurrent:true,authorityCeiling:"automatic",expectedAssignmentEpoch:5}),env);expect(response.status).toBe(409);const warning=(await response.json() as any).warning;expect(warning).toMatchObject({assignmentEpoch:5,currentActiveRevisionId:firstRevision,materializedRepositoryIds:["10","11"]});expect(warning.repositories).toHaveLength(1);expect(sqlite.prepare("SELECT COUNT(*) count FROM agent_repository_assignments WHERE agent_id='agent-one'").get()).toEqual({count:0});
    sqlite.prepare("UPDATE settings SET value='6' WHERE key='assignment_epoch'").run();response=await app.request("https://g.test/api/agents/agent-one/assignments",request("POST",{allCurrent:true,authorityCeiling:"automatic",expectedAssignmentEpoch:5,overlapFingerprint:warning.fingerprint,expectedActiveRevisionId:firstRevision,materializedRepositoryIds:["10","11"]}),env);expect(response.status).toBe(409);expect(sqlite.prepare("SELECT COUNT(*) count FROM agent_repository_assignments WHERE agent_id='agent-one'").get()).toEqual({count:0});expect(sqlite.prepare("SELECT COUNT(*) count FROM agent_repository_assignment_history WHERE assignment_id LIKE 'assignment_%'").get()).toEqual({count:2});
    response=await app.request("https://g.test/api/agents/agent-one/assignments",request("POST",{allCurrent:true,authorityCeiling:"automatic",expectedAssignmentEpoch:6}),env);const fresh=(await response.json() as any).warning;response=await app.request("https://g.test/api/agents/agent-one/assignments",request("POST",{allCurrent:true,authorityCeiling:"automatic",expectedAssignmentEpoch:6,overlapFingerprint:fresh.fingerprint,expectedActiveRevisionId:firstRevision,materializedRepositoryIds:["10","11"]}),env);expect(response.status).toBe(201);expect((await response.json() as any).assignments).toHaveLength(2);expect(sqlite.prepare("SELECT COUNT(*) count FROM agent_repository_assignments WHERE agent_id='agent-one'").get()).toEqual({count:2});expect(sqlite.prepare("SELECT value FROM settings WHERE key='assignment_epoch'").get()).toEqual({value:"7"});expect((sqlite.prepare("SELECT reason FROM agent_repository_assignment_history WHERE assignment_id IN (SELECT id FROM agent_repository_assignments WHERE agent_id='agent-one') LIMIT 1").get() as {reason:string}).reason).toBe(`overlap-confirmed:${fresh.fingerprint}`);
  }finally{sqlite.close()}});
  it("allows only an owner to completely configure a missing repository policy",async()=>{const{sqlite,env,app}=setup();try{
    const operationModes=Object.fromEntries(operationKindSchema.options.map(key=>[key,"disabled"]));const workspaceModes=Object.fromEntries(workspaceCapabilityValues.map(key=>[key,"disabled"]));const body={expectedPolicyVersion:1,expectedPolicyHash:null,operationModes,allowedObservations:[] as typeof observationCapabilityValues[number][],workspaceModes};
    expect((await app.request("https://g.test/api/repositories/10/policy",request("PUT",body,"member"),env)).status).toBe(403);expect((await app.request("https://g.test/api/repositories/10/policy",request("PUT",body,"mcp"),env)).status).toBe(403);
    sqlite.prepare("INSERT INTO repository_operation_policies(repository_id,operation_kind,mode,policy_version)VALUES('10','issue.close','disabled',1)").run();
    let response=await app.request("https://g.test/api/repositories/10/policy",request("PUT",body),env);expect(response.status).toBe(200);const configured=await response.json() as any;expect(configured).toMatchObject({result:"updated",policy:{configured:true,repository:{name:"acme/widgets"}}});
    const auditCount=sqlite.prepare("SELECT COUNT(*) count FROM audit_records WHERE action='repository.policy_updated'").get();response=await app.request("https://g.test/api/repositories/10/policy",request("PUT",{...body,expectedPolicyVersion:2,expectedPolicyHash:configured.policy.policyHash}),env);expect(await response.json()).toMatchObject({result:"noop"});expect(sqlite.prepare("SELECT value FROM settings WHERE key='policy_version'").get()).toEqual({value:"2"});expect(sqlite.prepare("SELECT COUNT(*) count FROM audit_records WHERE action='repository.policy_updated'").get()).toEqual(auditCount);
    expect(sqlite.prepare("SELECT COUNT(*) count FROM repository_operation_policies WHERE repository_id='10'").get()).toEqual({count:operationKindSchema.options.length});expect(sqlite.prepare("SELECT COUNT(*) count FROM repository_capability_policies WHERE repository_id='10'").get()).toEqual({count:observationCapabilityValues.length+workspaceCapabilityValues.length});
  }finally{sqlite.close()}});
});
