import { lstat, mkdir, readFile, readdir, rename, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { z } from "zod";
import {
  compileGitHubActionsTask,
  GITHUB_ACTIONS_TARGET,
  GITHUB_PERMISSION_KEYS,
  type GitHubActionsTaskPlanV1,
  type GitHubActionsTriggerBindingV1,
} from "./actions-target.js";
import { compileTaskSource, type CompiledTask } from "./task-authoring.js";

export const DEFAULT_WORKFLOW_REF =
  "scuffi/gardener/.github/workflows/gardener-task.yml@c835d6cd22a1315dc383692d2ad30753ad71b73d";
const GENERATED_MARKER = "# Generated by Gardener. Do not edit.";

const projectSchema = z.strictObject({
  schemaVersion: z.literal("gardener.project/v1"),
  target: z.literal(GITHUB_ACTIONS_TARGET),
  release: z.strictObject({
    workflowRef: z.string().regex(
      /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/\.github\/workflows\/[A-Za-z0-9_.\/-]+\.ya?ml@[0-9a-f]{40}$/,
    ),
  }),
});

interface BuiltTask extends CompiledTask {
  source: string;
  workflow: string;
  actionsPlan: GitHubActionsTaskPlanV1;
}

export interface ProjectBuildResult {
  lockPath: string;
  tasks: Array<{ taskId: string; bundleHash: string; workflow: string }>;
  /** Operator-facing warnings. Present but empty when nothing needs attention. */
  warnings: string[];
}

/**
 * Emitted for every task that declares `repository.exec`. Gardener does not
 * sandbox the GitHub-hosted runner, so such a task can reach any host and can
 * exfiltrate private source. This is a demo capability, not production-ready.
 */
export const UNRESTRICTED_EGRESS_WARNING =
  "declares repository.exec, which runs task-controlled commands with the GitHub-hosted runner's "
  + "unrestricted network egress. Gardener does not sandbox or filter that traffic, so the task can "
  + "reach any host and can exfiltrate private source. This is demo-only and is not production-ready.";

const BUG_INTAKE_TASK = `---
schema: gardener.task/v1
id: bug-intake
name: Bug intake
description: Inspects repository conventions and helps issue authors provide actionable bug reports.
trigger:
  event: github.issue.opened
  labels-all:
    - gardener-bug
tools:
  - repository.list_files
  - repository.read_file
effects:
  - issue.comment.create
network:
  default: deny
  allow: []
  deny: []
limits:
  runtime-seconds: 300
  max-turns: 16
  max-tool-calls: 12
  input-tokens: 60000
  output-tokens: 4000
---
Inspect the issue and the repository's relevant conventions.

Propose one concise issue comment containing:

1. The likely affected area.
2. Missing reproduction information.
3. Relevant test locations.
4. A concrete next step for the author or maintainer.

Do not claim that code was changed or that a persistent effect already occurred.
`;

const DOCS_HELPER_TASK = `---
schema: gardener.task/v1
id: docs-helper
name: Documentation helper
description: Locates relevant documentation and suggests a concrete documentation plan.
trigger:
  event: github.issue.opened
  labels-all:
    - gardener-docs
tools:
  - repository.list_files
  - repository.read_file
effects:
  - issue.comment.create
network:
  default: deny
  allow: []
  deny: []
limits:
  runtime-seconds: 300
  max-turns: 16
  max-tool-calls: 12
  input-tokens: 60000
  output-tokens: 4000
---
Inspect the issue and the repository's documentation structure.

Propose one concise issue comment containing:

1. The documentation files most likely involved.
2. Related guidance already present in the repository.
3. Missing information needed from the issue author.
4. A concrete documentation update plan.

Do not claim that documentation was changed or that a persistent effect already occurred.
`;

export async function initializeProject(input: {
  repositoryRoot: string;
  demos: boolean;
}): Promise<{ created: string[]; preserved: string[] }> {
  const root = resolve(input.repositoryRoot);
  const created: string[] = [];
  const preserved: string[] = [];
  const files = new Map<string, string>([
    [".gardener/gardener.json", `${JSON.stringify({
      schemaVersion: "gardener.project/v1",
      target: GITHUB_ACTIONS_TARGET,
      release: { workflowRef: DEFAULT_WORKFLOW_REF },
    }, null, 2)}\n`],
  ]);
  if (input.demos) {
    files.set(".gardener/tasks/bug-intake/TASK.md", BUG_INTAKE_TASK);
    files.set(".gardener/tasks/docs-helper/TASK.md", DOCS_HELPER_TASK);
  }
  for (const [path, content] of files) {
    const target = join(root, path);
    await mkdir(dirname(target), { recursive: true });
    if (await exists(target)) {
      preserved.push(path);
      continue;
    }
    await atomicWrite(target, content);
    created.push(path);
  }
  return { created, preserved };
}

export async function upgradeProjectRelease(input: { repositoryRoot: string }): Promise<{
  previousWorkflowRef: string;
  workflowRef: string;
  changed: boolean;
}> {
  const root = resolve(input.repositoryRoot);
  const projectPath = join(root, ".gardener", "gardener.json");
  let source: string;
  try {
    source = await readFile(projectPath, "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      throw new Error(`Not a Gardener project: ${root}. Pass --repository-root for a repository containing .gardener/gardener.json`);
    }
    throw error;
  }
  const project = projectSchema.parse(JSON.parse(source));
  const previousWorkflowRef = project.release.workflowRef;
  if (previousWorkflowRef !== DEFAULT_WORKFLOW_REF) {
    await atomicWrite(projectPath, `${JSON.stringify({
      ...project,
      release: { ...project.release, workflowRef: DEFAULT_WORKFLOW_REF },
    }, null, 2)}\n`);
  }
  return {
    previousWorkflowRef,
    workflowRef: DEFAULT_WORKFLOW_REF,
    changed: previousWorkflowRef !== DEFAULT_WORKFLOW_REF,
  };
}

export async function buildProject(input: { repositoryRoot: string }): Promise<ProjectBuildResult> {
  const root = resolve(input.repositoryRoot);
  const gardenerDirectory = join(root, ".gardener");
  const projectPath = join(gardenerDirectory, "gardener.json");
  const project = projectSchema.parse(JSON.parse(await readFile(projectPath, "utf8")));
  const taskRoot = join(gardenerDirectory, "tasks");
  const entries = (await readdir(taskRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name));
  if (entries.length === 0) throw new Error("No .gardener/tasks/*/TASK.md files were found");

  const tasks: BuiltTask[] = [];
  const taskIds = new Set<string>();
  const workflows = new Set<string>();
  for (const entry of entries) {
    const taskPath = join(taskRoot, entry.name, "TASK.md");
    const taskStat = await lstat(taskPath);
    if (!taskStat.isFile() || taskStat.isSymbolicLink()) {
      throw new Error(`${relative(root, taskPath)} is not a regular file`);
    }
    const source = relative(gardenerDirectory, taskPath).replaceAll("\\", "/");
    const compiled = await compileTaskSource(await readFile(taskPath, "utf8"), source);
    if (taskIds.has(compiled.bundle.taskId)) throw new Error(`Duplicate task id: ${compiled.bundle.taskId}`);
    taskIds.add(compiled.bundle.taskId);
    const workflow = `.github/workflows/gardener-${workflowSlug(compiled.bundle.taskId)}.yml`;
    if (workflows.has(workflow)) throw new Error(`Multiple tasks generate ${workflow}`);
    workflows.add(workflow);
    tasks.push({
      ...compiled,
      source,
      workflow,
      actionsPlan: compileGitHubActionsTask(compiled.bundle),
    });
  }
  tasks.sort((left, right) => left.bundle.taskId.localeCompare(right.bundle.taskId));

  const previous = await readPreviousLock(join(gardenerDirectory, "gardener.lock.json"));
  const nextWorkflows = new Set(tasks.map((task) => task.workflow));
  for (const stale of previous.filter((path) => !nextWorkflows.has(path))) {
    const target = join(root, stale);
    if (await exists(target) && (await readFile(target, "utf8")).startsWith(GENERATED_MARKER)) {
      await unlink(target);
    }
  }

  for (const task of tasks) {
    const output = join(root, task.workflow);
    await mkdir(dirname(output), { recursive: true });
    if (await exists(output) && !(await readFile(output, "utf8")).startsWith(GENERATED_MARKER)) {
      throw new Error(`Refusing to overwrite non-Gardener workflow ${task.workflow}`);
    }
    await atomicWrite(output, renderTaskWorkflow(task, project.release.workflowRef));
  }

  const lock = {
    schemaVersion: "gardener.lock/v1",
    target: {
      id: project.target,
      adapterVersion: "1",
      workflowRef: project.release.workflowRef,
    },
    release: project.release,
    tasks: Object.fromEntries(tasks.map((task) => [task.bundle.taskId, {
      source: task.source,
      bundleHash: task.bundleHash,
      workflow: task.workflow,
      bundle: task.bundle,
      deployment: task.actionsPlan,
    }])),
  };
  const lockPath = join(gardenerDirectory, "gardener.lock.json");
  await atomicWrite(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
  const warnings = tasks
    .filter((task) => task.bundle.tools.includes("repository.exec"))
    .map((task) => `Task ${task.bundle.taskId} ${UNRESTRICTED_EGRESS_WARNING}`);
  return {
    warnings,
    lockPath,
    tasks: tasks.map((task) => ({
      taskId: task.bundle.taskId,
      bundleHash: task.bundleHash,
      workflow: task.workflow,
    })),
  };
}

/** Canonical GitHub event ordering so regenerated workflows stay byte-identical. */
const WORKFLOW_EVENT_ORDER = [
  "issues",
  "issue_comment",
  "pull_request",
  "pull_request_review",
  "pull_request_review_comment",
  "push",
  "discussion",
  "discussion_comment",
  "schedule",
  "workflow_dispatch",
] as const;

function renderWorkflowTriggers(task: BuiltTask): string {
  const bindings = task.actionsPlan.triggers;
  const lines: string[] = [];
  for (const event of WORKFLOW_EVENT_ORDER) {
    const matching = bindings.filter((binding) => binding.event === event);
    if (matching.length === 0) continue;
    if (event === "schedule") {
      lines.push("  schedule:");
      const crons = task.bundle.triggers
        .filter((trigger) => trigger.kind === "github.schedule")
        .map((trigger) => (trigger as { cron: string }).cron);
      for (const cron of crons) lines.push(`    - cron: ${yamlString(cron)}`);
      continue;
    }
    if (event === "push") {
      const branches = task.bundle.triggers
        .filter((trigger) => trigger.kind === "github.push")
        .flatMap((trigger) => (trigger as { branches: string[] }).branches);
      lines.push("  push:");
      lines.push("    branches:");
      for (const branch of branches) lines.push(`      - ${yamlString(branch)}`);
      continue;
    }
    if (event === "workflow_dispatch") {
      // The runner requires a non-empty `prompt` input and rejects anything
      // longer than 20,000 characters, so the generated form declares it
      // required with no default. A default would let an empty dispatch start
      // a run that the parser then fails, which reads as a Gardener bug.
      lines.push("  workflow_dispatch:");
      lines.push("    inputs:");
      lines.push("      prompt:");
      lines.push("        description: What this run should do. Required, 1 to 20000 characters.");
      lines.push("        required: true");
      lines.push("        type: string");
      continue;
    }
    const types = matching
      .map((binding) => binding.action)
      .filter((action): action is string => action !== undefined);
    lines.push(`  ${event}:`);
    lines.push(`    types: [${types.join(", ")}]`);
  }
  return lines.join("\n");
}

function renderTriggerCondition(binding: GitHubActionsTriggerBindingV1, task: BuiltTask): string {
  const clauses = [`github.event_name == '${binding.event}'`];
  if (binding.action !== undefined) clauses.push(`github.event.action == '${binding.action}'`);
  if (binding.forkSensitive) {
    // Unconditional in V1: fork-owned head revisions are never planned, and the
    // runtime re-checks head repository identity even if this file is edited.
    clauses.push("github.event.pull_request.head.repo.full_name == github.repository");
  }
  const trigger = task.bundle.triggers.find((candidate) => candidate.kind === binding.kind);
  const labels = trigger && "labelsAll" in trigger ? trigger.labelsAll : [];
  if (binding.labelsExpression !== undefined) {
    for (const label of labels) {
      clauses.push(`contains(${binding.labelsExpression}, ${yamlSingleQuoted(label)})`);
    }
  }
  return clauses.length === 1 ? clauses[0]! : `(${clauses.join(" && ")})`;
}

function renderJobCondition(task: BuiltTask): string {
  const conditions = task.actionsPlan.triggers.map((binding) => renderTriggerCondition(binding, task));
  return conditions.join("\n        || ");
}

function renderPermissions(task: BuiltTask): string {
  const permissions = task.actionsPlan.callerPermissions;
  return GITHUB_PERMISSION_KEYS
    .filter((key) => permissions[key] !== undefined)
    .map((key) => `      ${key}: ${permissions[key]}`)
    .join("\n");
}

function renderTaskWorkflow(task: BuiltTask, workflowRef: string): string {
  return `${GENERATED_MARKER}
#
# Source: .gardener/${task.source}
# Task: ${task.bundle.taskId}
# Bundle: sha256:${task.bundleHash}
# Regenerate: gardener build
# Do not edit this workflow directly.
name: ${yamlString(`Gardener · ${task.bundle.name}`)}

on:
${renderWorkflowTriggers(task)}

permissions: {}

jobs:
  gardener:
    if: >-
      \${{
        ${renderJobCondition(task)}
      }}
    permissions:
${renderPermissions(task)}
    uses: ${workflowRef}
    with:
      runtime-url: \${{ vars.GARDENER_RUNTIME_URL }}
      task-id: ${yamlString(task.bundle.taskId)}
      task-name: ${yamlString(task.bundle.name)}
      task-source: ${yamlString(`.gardener/${task.source}`)}
      task-bundle-hash: ${task.bundleHash}
`;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

/** GitHub expression string literal. Labels are constrained to a safe character set. */
function yamlSingleQuoted(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function workflowSlug(taskId: string): string {
  return taskId.replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
}

async function readPreviousLock(path: string): Promise<string[]> {
  if (!await exists(path)) return [];
  try {
    const value = JSON.parse(await readFile(path, "utf8")) as { tasks?: Record<string, { workflow?: unknown }> };
    return Object.values(value.tasks ?? {})
      .map((task) => task.workflow)
      .filter((workflow): workflow is string => typeof workflow === "string");
  } catch {
    throw new Error("Existing .gardener/gardener.lock.json is invalid");
  }
}

async function atomicWrite(path: string, content: string): Promise<void> {
  if (await exists(path) && await readFile(path, "utf8") === content) return;
  const temporary = `${path}.tmp-${process.pid}`;
  await writeFile(temporary, content, { encoding: "utf8", mode: 0o644 });
  await rename(temporary, path);
}

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") return false;
    throw error;
  }
}
