import { lstat, mkdir, readFile, readdir, rename, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { z } from "zod";
import {
  authoredTriggerSubject,
  checkWorkflowRefFor,
  checksOutPullRequestHead,
  syncWorkflowRefFor,
  dispatchTargetKinds,
  githubHandleV1Schema,
  isAuthoredTriggerKind,
  isEditedTriggerKind,
  type AuthoredTriggerKindV1,
} from "@gardener/contracts";
import {
  compileGitHubActionsTask,
  GITHUB_ACTIONS_TARGET,
  GITHUB_PERMISSION_KEYS,
  planTimeoutMinutes,
  type GitHubActionsTaskPlanV1,
  type GitHubActionsTriggerBindingV1,
} from "./actions-target.js";
import { compileTaskSource, modelWarning, type CompiledTask } from "./task-authoring.js";
import { renderTaskGuide, TASK_GUIDE_PATH } from "./task-guide.js";

export const DEFAULT_WORKFLOW_REF =
  "scuffi/gardener/.github/workflows/gardener-task.yml@de534dff93a56527b45db8f46aedac72c8911da0";
export const GENERATED_MARKER = "# Generated by Gardener. Do not edit.";
/** The generated workflow that enrols the committed tasks on each push to the default branch. */
export const SYNC_WORKFLOW = ".github/workflows/gardener-sync.yml";

const projectSchema = z.strictObject({
  schemaVersion: z.literal("gardener.project/v1"),
  target: z.literal(GITHUB_ACTIONS_TARGET),
  release: z.strictObject({
    workflowRef: z.string().regex(
      /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/\.github\/workflows\/[A-Za-z0-9_.\/-]+\.ya?ml@[0-9a-f]{40}$/,
    ),
  }),
  /**
   * The GitHub handle people @mention to reach this project's tasks, such as a
   * bot account. `mentions: [self]` in a TASK.md resolves to it.
   */
  handle: z.string().transform((value) => value.replace(/^@/, "").toLowerCase()).pipe(githubHandleV1Schema).optional(),
});

interface BuiltTask extends CompiledTask {
  source: string;
  workflow: string;
  actionsPlan: GitHubActionsTaskPlanV1;
}

export interface ProjectBuildResult {
  lockPath: string;
  tasks: Array<{ taskId: string; bundleHash: string; workflow: string }>;
  /** The task-writing skill, when this build created or changed it. */
  guidePath?: string;
  /** Operator-facing warnings. Present but empty when nothing needs attention. */
  warnings: string[];
}

/**
 * Emitted for every task that declares `repository.exec`. Gardener does not
 * sandbox the GitHub-hosted runner, so such a task can reach any host and can
 * exfiltrate private source. This is a demo capability, not production-ready.
 */
export const UNRESTRICTED_EGRESS_WARNING =
  "declares repository.exec, which runs task-controlled commands with the GitHub-hosted runner's "
  + "unrestricted network egress. Gardener does not sandbox or filter that traffic, so the task can "
  + "reach any host and can exfiltrate private source. This is demo-only and is not production-ready.";

const BUG_INTAKE_TASK = `---
schema: gardener.task/v1
id: bug-intake
name: Bug intake
description: Inspects repository conventions and helps issue authors provide actionable bug reports.
trigger:
  event: github.issue.opened
  labels-all:
    - gardener-bug
tools:
  - repository.list_files
  - repository.read_file
effects:
  - issue.comment.create
network:
  default: deny
  allow: []
  deny: []
limits:
  runtime-seconds: 300
  max-turns: 16
  max-tool-calls: 12
  input-tokens: 60000
  output-tokens: 16000
---
Inspect the issue and the repository's relevant conventions.

Propose one concise issue comment containing:

1. The likely affected area.
2. Missing reproduction information.
3. Relevant test locations.
4. A concrete next step for the author or maintainer.

Do not claim that code was changed or that a persistent effect already occurred.
`;

const DOCS_HELPER_TASK = `---
schema: gardener.task/v1
id: docs-helper
name: Documentation helper
description: Locates relevant documentation and suggests a concrete documentation plan.
trigger:
  event: github.issue.opened
  labels-all:
    - gardener-docs
tools:
  - repository.list_files
  - repository.read_file
effects:
  - issue.comment.create
network:
  default: deny
  allow: []
  deny: []
limits:
  runtime-seconds: 300
  max-turns: 16
  max-tool-calls: 12
  input-tokens: 60000
  output-tokens: 16000
---
Inspect the issue and the repository's documentation structure.

Propose one concise issue comment containing:

1. The documentation files most likely involved.
2. Related guidance already present in the repository.
3. Missing information needed from the issue author.
4. A concrete documentation update plan.

Do not claim that documentation was changed or that a persistent effect already occurred.
`;

export async function initializeProject(input: {
  repositoryRoot: string;
  demos: boolean;
}): Promise<{ created: string[]; preserved: string[] }> {
  const root = resolve(input.repositoryRoot);
  const created: string[] = [];
  const preserved: string[] = [];
  const files = new Map<string, string>([
    [".gardener/gardener.json", `${JSON.stringify({
      schemaVersion: "gardener.project/v1",
      target: GITHUB_ACTIONS_TARGET,
      release: { workflowRef: DEFAULT_WORKFLOW_REF },
    }, null, 2)}\n`],
    [TASK_GUIDE_PATH, await renderTaskGuide()],
  ]);
  if (input.demos) {
    files.set(".gardener/tasks/bug-intake/TASK.md", BUG_INTAKE_TASK);
    files.set(".gardener/tasks/docs-helper/TASK.md", DOCS_HELPER_TASK);
  }
  for (const [path, content] of files) {
    const target = join(root, path);
    await mkdir(dirname(target), { recursive: true });
    if (await exists(target)) {
      preserved.push(path);
      continue;
    }
    await atomicWrite(target, content);
    created.push(path);
  }
  return { created, preserved };
}

/** Throws unless `repositoryRoot` holds `.gardener/gardener.json`. Reads nothing else. */
export async function requireProject(repositoryRoot: string): Promise<void> {
  const root = resolve(repositoryRoot);
  if (!await exists(join(root, ".gardener", "gardener.json"))) {
    throw new Error(`Not a Gardener project: ${root}. Pass --repository-root for a repository containing .gardener/gardener.json`);
  }
}

export async function upgradeProjectRelease(input: { repositoryRoot: string }): Promise<{
  previousWorkflowRef: string;
  workflowRef: string;
  changed: boolean;
}> {
  const root = resolve(input.repositoryRoot);
  const projectPath = join(root, ".gardener", "gardener.json");
  let source: string;
  try {
    source = await readFile(projectPath, "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      throw new Error(`Not a Gardener project: ${root}. Pass --repository-root for a repository containing .gardener/gardener.json`);
    }
    throw error;
  }
  const project = projectSchema.parse(JSON.parse(source));
  const previousWorkflowRef = project.release.workflowRef;
  if (previousWorkflowRef !== DEFAULT_WORKFLOW_REF) {
    await atomicWrite(projectPath, `${JSON.stringify({
      ...project,
      release: { ...project.release, workflowRef: DEFAULT_WORKFLOW_REF },
    }, null, 2)}\n`);
  }
  return {
    previousWorkflowRef,
    workflowRef: DEFAULT_WORKFLOW_REF,
    changed: previousWorkflowRef !== DEFAULT_WORKFLOW_REF,
  };
}

/**
 * Moves `package.json` scripts that run a pinned Gardener CLI (such as
 * `"gardener:generate": "npx --yes @scuffi/gardener@0.1.4 generate"`) to this
 * release, so contributors generate with the same compiler as the pinned
 * workflows. Only script values are matched; each is replaced as text, which
 * keeps the file's formatting but also rewrites an identical string elsewhere
 * in the file. Returns the names of the scripts it changed.
 */
export async function pinCliScripts(input: {
  repositoryRoot: string;
  version: string;
  packageName?: string;
}): Promise<string[]> {
  const packagePath = join(resolve(input.repositoryRoot), "package.json");
  let source: string;
  try {
    source = await readFile(packagePath, "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") return [];
    throw error;
  }
  const scripts = (JSON.parse(source) as { scripts?: unknown }).scripts;
  if (!scripts || typeof scripts !== "object") return [];
  const name = (input.packageName ?? "@scuffi/gardener").replace(/[.*+?^${}()|[\]\\/]/g, "\\$&");
  const pinned = new RegExp(`${name}@\\d+\\.\\d+\\.\\d+(?:-[0-9A-Za-z.-]+)?(?![0-9A-Za-z.-])`, "g");
  const changed: string[] = [];
  let next = source;
  for (const [script, value] of Object.entries(scripts)) {
    if (typeof value !== "string") continue;
    const updated = value.replace(pinned, `${input.packageName ?? "@scuffi/gardener"}@${input.version}`);
    if (updated === value) continue;
    const before = JSON.stringify(value);
    if (next.includes(before)) next = next.replaceAll(before, JSON.stringify(updated));
    // A script sharing its value with an earlier one was rewritten with it.
    if (!next.includes(before)) changed.push(script);
  }
  if (next !== source) await atomicWrite(packagePath, next);
  return changed;
}

/**
 * Everything `generate` writes, computed without writing: the lock, one
 * workflow per task and the sync workflow, as paths relative to the
 * repository root. The sync bridge compares it with the committed files.
 */
export interface ProjectPlan {
  root: string;
  workflowRef: string;
  files: Array<{ path: string; content: string }>;
  tasks: Array<{ taskId: string; source: string; bundleHash: string; workflow: string; bundle: unknown }>;
  warnings: string[];
}

export async function planProject(input: { repositoryRoot: string }): Promise<ProjectPlan> {
  const root = resolve(input.repositoryRoot);
  const gardenerDirectory = join(root, ".gardener");
  const projectPath = join(gardenerDirectory, "gardener.json");
  const project = projectSchema.parse(JSON.parse(await readFile(projectPath, "utf8")));
  const taskRoot = join(gardenerDirectory, "tasks");
  // No tasks is a valid project: deleting the last one must reach the
  // default branch, where the sync then stops everything.
  const entries = (await readdir(taskRoot, { withFileTypes: true }).catch((error: unknown) => {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") return [];
    throw error;
  }))
    .filter((entry) => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name));

  const tasks: BuiltTask[] = [];
  const taskIds = new Set<string>();
  const workflows = new Set<string>([SYNC_WORKFLOW]);
  for (const entry of entries) {
    const taskPath = join(taskRoot, entry.name, "TASK.md");
    const taskStat = await lstat(taskPath);
    if (!taskStat.isFile() || taskStat.isSymbolicLink()) {
      throw new Error(`${relative(root, taskPath)} is not a regular file`);
    }
    const source = relative(gardenerDirectory, taskPath).replaceAll("\\", "/");
    const compiled = await compileTaskSource(await readFile(taskPath, "utf8"), source, project.handle === undefined ? {} : { handle: project.handle });
    if (taskIds.has(compiled.bundle.taskId)) throw new Error(`Duplicate task id: ${compiled.bundle.taskId}`);
    taskIds.add(compiled.bundle.taskId);
    const workflow = `.github/workflows/gardener-${workflowSlug(compiled.bundle.taskId)}.yml`;
    if (workflow === SYNC_WORKFLOW) throw new Error(`Task ${compiled.bundle.taskId} would overwrite ${SYNC_WORKFLOW}; rename it`);
    if (workflows.has(workflow)) throw new Error(`Multiple tasks generate ${workflow}`);
    workflows.add(workflow);
    tasks.push({
      ...compiled,
      source,
      workflow,
      actionsPlan: compileGitHubActionsTask(compiled.bundle),
    });
  }
  tasks.sort((left, right) => left.bundle.taskId.localeCompare(right.bundle.taskId));

  const lock = {
    schemaVersion: "gardener.lock/v1",
    target: {
      id: project.target,
      adapterVersion: "1",
      workflowRef: project.release.workflowRef,
    },
    release: project.release,
    tasks: Object.fromEntries(tasks.map((task) => [task.bundle.taskId, {
      source: task.source,
      bundleHash: task.bundleHash,
      workflow: task.workflow,
      bundle: task.bundle,
      deployment: task.actionsPlan,
    }])),
  };
  const setsPlanTimeout = definesPlanTimeout(project.release.workflowRef);
  const warnings = [
    ...(tasks.length === 0
      ? ["No .gardener/tasks/*/TASK.md files were found. Once this reaches the default branch, no Gardener task runs."]
      : []),
    ...tasks
      .filter((task) => task.bundle.tools.includes("repository.exec"))
      .map((task) => `Task ${task.bundle.taskId} ${UNRESTRICTED_EGRESS_WARNING}`),
    ...tasks.flatMap((task) => {
      const warning = modelWarning(task.bundle.model);
      return warning === undefined ? [] : [`Task ${task.bundle.taskId} ${warning}`];
    }),
    ...(setsPlanTimeout ? [] : tasks
      .filter((task) => task.bundle.limits.runtimeSeconds > LEGACY_MAX_RUNTIME_SECONDS)
      .map((task) => `Task ${task.bundle.taskId} runs for up to ${task.bundle.limits.runtimeSeconds} seconds, but this project pins an earlier Gardener release, whose plan job stops after ${LEGACY_PLAN_TIMEOUT_MINUTES} minutes. Run gardener upgrade to use this release's workflows.`)),
  ];
  return {
    root,
    workflowRef: project.release.workflowRef,
    files: [
      ...tasks.map((task) => ({ path: task.workflow, content: renderTaskWorkflow(task, project.release.workflowRef, setsPlanTimeout) })),
      { path: SYNC_WORKFLOW, content: renderSyncWorkflow(project.release.workflowRef) },
      { path: ".gardener/gardener.lock.json", content: `${JSON.stringify(lock, null, 2)}\n` },
    ],
    tasks: tasks.map((task) => ({
      taskId: task.bundle.taskId,
      source: task.source,
      bundleHash: task.bundleHash,
      workflow: task.workflow,
      bundle: task.bundle,
    })),
    warnings,
  };
}

/**
 * The committed files that differ from `plan`: changed, missing, or a
 * generated workflow no task produces any more. Empty when `generate` would
 * change nothing.
 */
export async function staleProjectFiles(plan: ProjectPlan): Promise<string[]> {
  const stale: string[] = [];
  for (const file of plan.files) {
    const current = await readFile(join(plan.root, file.path), "utf8").catch(() => null);
    if (current !== file.content) stale.push(current === null ? `${file.path} (missing)` : file.path);
  }
  const planned = new Set(plan.files.map((file) => file.path));
  const names = await readdir(join(plan.root, ".github/workflows")).catch(() => [] as string[]);
  for (const name of names.sort()) {
    const path = `.github/workflows/${name}`;
    if (!/^gardener-.+\.ya?ml$/.test(name) || planned.has(path)) continue;
    if ((await readFile(join(plan.root, path), "utf8")).startsWith(GENERATED_MARKER)) stale.push(`${path} (no longer generated)`);
  }
  return stale;
}

export async function buildProject(input: { repositoryRoot: string }): Promise<ProjectBuildResult> {
  const plan = await planProject(input);
  const root = plan.root;
  const lockPath = join(root, ".gardener", "gardener.lock.json");
  const previous = await readPreviousLock(lockPath);
  const planned = new Set(plan.files.map((file) => file.path));
  for (const stale of previous.filter((path) => !planned.has(path))) {
    const target = join(root, stale);
    if (await exists(target) && (await readFile(target, "utf8")).startsWith(GENERATED_MARKER)) {
      await unlink(target);
    }
  }
  for (const file of plan.files) {
    const output = join(root, file.path);
    await mkdir(dirname(output), { recursive: true });
    if (file.path.startsWith(".github/") && await exists(output)
      && !(await readFile(output, "utf8")).startsWith(GENERATED_MARKER)) {
      throw new Error(`Refusing to overwrite non-Gardener workflow ${file.path}`);
    }
    await atomicWrite(output, file.content);
  }
  // Not part of the plan: a stale guide must never fail the pull request
  // check or the sync, it is refreshed whenever anyone generates.
  const guidePath = join(root, TASK_GUIDE_PATH);
  const guide = await renderTaskGuide();
  const guideChanged = await readFile(guidePath, "utf8").catch(() => null) !== guide;
  if (guideChanged) await atomicWrite(guidePath, guide);
  return {
    warnings: plan.warnings,
    lockPath,
    ...(guideChanged ? { guidePath } : {}),
    tasks: plan.tasks.map(({ taskId, bundleHash, workflow }) => ({ taskId, bundleHash, workflow })),
  };
}

/** Canonical GitHub event ordering so regenerated workflows stay byte-identical. */
const WORKFLOW_EVENT_ORDER = [
  "issues",
  "issue_comment",
  "pull_request",
  "pull_request_review",
  "pull_request_review_comment",
  "push",
  "discussion",
  "discussion_comment",
  "schedule",
  "workflow_dispatch",
] as const;

function renderWorkflowTriggers(task: BuiltTask): string {
  const bindings = task.actionsPlan.triggers;
  const lines: string[] = [];
  for (const event of WORKFLOW_EVENT_ORDER) {
    const matching = bindings.filter((binding) => binding.event === event);
    if (matching.length === 0) continue;
    if (event === "schedule") {
      lines.push("  schedule:");
      const crons = task.bundle.triggers
        .filter((trigger) => trigger.kind === "github.schedule")
        .map((trigger) => (trigger as { cron: string }).cron);
      for (const cron of crons) lines.push(`    - cron: ${yamlString(cron)}`);
      continue;
    }
    if (event === "push") {
      const branches = task.bundle.triggers
        .filter((trigger) => trigger.kind === "github.push")
        .flatMap((trigger) => (trigger as { branches: string[] }).branches);
      lines.push("  push:");
      lines.push("    branches:");
      for (const branch of branches) lines.push(`      - ${yamlString(branch)}`);
      continue;
    }
    if (event === "workflow_dispatch") {
      // Every input is optional. With none, the run follows the task's
      // instructions alone; a target input names the issue or pull request to
      // act on, offered for the resources the task's other triggers act on.
      lines.push("  workflow_dispatch:");
      lines.push("    inputs:");
      lines.push("      prompt:");
      lines.push("        description: Extra instructions for this run. Optional, up to 20000 characters.");
      lines.push("        required: false");
      lines.push("        type: string");
      for (const target of dispatchTargetKinds(task.bundle.triggers)) {
        lines.push(`      ${target}:`);
        lines.push(`        description: ${target === "issue" ? "Issue" : "Pull request"} number to run against. Optional.`);
        lines.push("        required: false");
        lines.push("        type: string");
      }
      continue;
    }
    const types = matching
      .map((binding) => binding.action)
      .filter((action): action is string => action !== undefined);
    lines.push(`  ${event}:`);
    lines.push(`    types: [${types.join(", ")}]`);
  }
  return lines.join("\n");
}

function renderTriggerCondition(binding: GitHubActionsTriggerBindingV1, task: BuiltTask): string {
  const clauses = [`github.event_name == '${binding.event}'`];
  if (binding.action !== undefined) clauses.push(`github.event.action == '${binding.action}'`);
  if (binding.forkSensitive) {
    // Unconditional in V1: fork-owned head revisions are never planned, and the
    // runtime re-checks head repository identity even if this file is edited.
    clauses.push("github.event.pull_request.head.repo.full_name == github.repository");
  }
  const trigger = task.bundle.triggers.find((candidate) => candidate.kind === binding.kind);
  const labels = trigger && "labelsAll" in trigger ? trigger.labelsAll : [];
  if (binding.labelsExpression !== undefined) {
    for (const label of labels) {
      clauses.push(`contains(${binding.labelsExpression}, ${yamlSingleQuoted(label)})`);
    }
  }
  if (trigger !== undefined && "authors" in trigger && isAuthoredTriggerKind(trigger.kind)) {
    clauses.push(...authoredTriggerClauses(trigger.kind, trigger.mentions));
  }
  if (trigger !== undefined && "openedBy" in trigger && trigger.openedBy !== undefined) {
    clauses.push(openedByClause(binding.event, trigger.openedBy));
  }
  return clauses.length === 1 ? clauses[0]! : `(${clauses.join(" && ")})`;
}

const SUBJECT_EXPRESSIONS: Record<(typeof authoredTriggerSubject)[AuthoredTriggerKindV1], string> = {
  issue: "github.event.issue",
  comment: "github.event.comment",
  pullRequest: "github.event.pull_request",
  review: "github.event.review",
  discussion: "github.event.discussion",
};

/**
 * Prefilters for `mentions`. They skip the job for events that certainly don't
 * match, so they must never exclude one that does: the Worker makes the exact
 * decision (word boundaries, and whether an edit added the mention), and a run
 * that passes here but not there completes as a skip.
 *
 * `authors: maintainers` has no prefilter. GitHub reports a private org member
 * as a non-member, so only the bridge's permission lookup can tell, and an
 * `author_association` check here would skip them before it runs.
 */
function authoredTriggerClauses(
  kind: AuthoredTriggerKindV1,
  mentions: readonly string[],
): string[] {
  const subject = SUBJECT_EXPRESSIONS[authoredTriggerSubject[kind]];
  const clauses: string[] = [];
  if (mentions.length > 0) {
    // contains() is case-insensitive, like GitHub mentions. Handles are
    // letters, digits and hyphens, so they need no quoting.
    const any = mentions.map((handle) => `contains(${subject}.body, '@${handle}')`);
    clauses.push(any.length === 1 ? any[0]! : `(${any.join(" || ")})`);
    // An edit can only add a mention if it changed the body.
    if (isEditedTriggerKind(kind)) clauses.push("github.event.changes.body");
  }
  return clauses;
}

/** Where each event carries the thread `opened-by` filters on. */
const THREAD_EXPRESSIONS: Partial<Record<GitHubActionsTriggerBindingV1["event"], string>> = {
  issues: "github.event.issue",
  issue_comment: "github.event.issue",
  pull_request: "github.event.pull_request",
  pull_request_review: "github.event.pull_request",
  pull_request_review_comment: "github.event.pull_request",
  discussion: "github.event.discussion",
  discussion_comment: "github.event.discussion",
};

/**
 * Prefilter for `opened-by`. GitHub's `==` on strings is case-insensitive and
 * the Worker compares lower-cased logins, so this never skips an event the
 * Worker would admit. Logins are letters, digits, hyphens and `[bot]`, so
 * they need no escaping inside single quotes.
 */
function openedByClause(event: GitHubActionsTriggerBindingV1["event"], logins: readonly string[]): string {
  const thread = THREAD_EXPRESSIONS[event];
  if (thread === undefined) throw new Error(`opened-by is not supported for ${event} events`);
  const any = logins.map((login) => `${thread}.user.login == '${login}'`);
  return any.length === 1 ? any[0]! : `(${any.join(" || ")})`;
}

function renderJobCondition(task: BuiltTask): string {
  const conditions = task.actionsPlan.triggers.map((binding) => renderTriggerCondition(binding, task));
  return conditions.join("\n        || ");
}

function renderPermissions(task: BuiltTask): string {
  const permissions = task.actionsPlan.callerPermissions;
  return GITHUB_PERMISSION_KEYS
    .filter((key) => permissions[key] !== undefined)
    .map((key) => `      ${key}: ${permissions[key]}`)
    .join("\n");
}

/**
 * The task workflows of releases before `plan-timeout-minutes` (0.1.0–0.1.7).
 * GitHub rejects every run of a caller that passes an input its workflow does
 * not define, so a project still pinned to one of these gets callers without
 * it. A fixed list rather than a comparison with DEFAULT_WORKFLOW_REF: the
 * sync and check bridges render callers too, and a bridge is built before the
 * commit that pins it, so it never knows its own release's ref.
 */
const TASK_WORKFLOWS_WITHOUT_PLAN_TIMEOUT = new Set([
  "ec7eded3ffeae332f745200e270f3601d8b35aa8",
  "aad5c2bb2560f5a2f9830f9ff4d9456dd48985a4",
  "ce457eb2b4ec4ea85f2e6e5dd9ce794d196da711",
  "3a0bc85d1f5cffccb50fba787b18334e4c21ba72",
]);

function definesPlanTimeout(workflowRef: string): boolean {
  return !TASK_WORKFLOWS_WITHOUT_PLAN_TIMEOUT.has(workflowRef.slice(workflowRef.lastIndexOf("@") + 1));
}

/** The plan job's timeout in releases before `plan-timeout-minutes`, and its default since. */
const LEGACY_PLAN_TIMEOUT_MINUTES = 10;
/** The longest run those releases allowed, which fits their plan job. */
const LEGACY_MAX_RUNTIME_SECONDS = 480;

function renderTaskWorkflow(task: BuiltTask, workflowRef: string, setsPlanTimeout: boolean): string {
  return `${GENERATED_MARKER}
#
# Source: .gardener/${task.source}
# Task: ${task.bundle.taskId}
# Bundle: sha256:${task.bundleHash}
# Regenerate: gardener generate
# Do not edit this workflow directly.
name: ${yamlString(`Gardener · ${task.bundle.name}`)}

on:
${renderWorkflowTriggers(task)}

permissions: {}

jobs:
  gardener:
    if: >-
      \${{
        ${renderJobCondition(task)}
      }}
${checksOutPullRequestHead(task.bundle)
  // One round per pull request at a time: two at once would build on the same
  // head, and the second push would be refused. Events without a pull request
  // fall back to their own run id, so they are never serialised.
  ? `    concurrency:\n      group: gardener-${task.bundle.taskId}-\${{ github.event.pull_request.number || github.run_id }}\n      cancel-in-progress: false\n`
  : ""}    permissions:
${renderPermissions(task)}
    uses: ${workflowRef}
    with:
      runtime-url: \${{ vars.GARDENER_RUNTIME_URL }}
      task-id: ${yamlString(task.bundle.taskId)}
      task-name: ${yamlString(task.bundle.name)}
      task-source: ${yamlString(`.gardener/${task.source}`)}
      task-bundle-hash: ${task.bundleHash}
${setsPlanTimeout ? `      plan-timeout-minutes: ${planTimeoutMinutes(task.bundle.limits.runtimeSeconds)}\n` : ""}${checksOutPullRequestHead(task.bundle)
  // Tasks that check out the pull request head (checkout: pull-request-head,
  // or commits beyond gardener/**) build on it, not GitHub's merge preview.
  // Empty for events without a pull request.
  ? "      checkout-ref: ${{ github.event.pull_request.head.sha }}\n"
  : ""}`;
}

/**
 * The caller for the pinned sync and check workflows. Pushes that touch
 * Gardener's files sync them; the runtime accepts a sync only from the default
 * branch, and the `if:` just saves a job on other branches. Pull requests that
 * touch them get a read-only check that the generated files are up to date, so
 * a forgotten `generate` shows up before merge rather than as a failed sync.
 */
function renderSyncWorkflow(workflowRef: string): string {
  const syncRef = syncWorkflowRefFor(workflowRef);
  const checkRef = checkWorkflowRefFor(workflowRef);
  if (syncRef === null || checkRef === null) throw new Error(`Cannot derive the sync workflow from ${workflowRef}`);
  return `${GENERATED_MARKER}
#
# Enrols the committed Gardener tasks when they change on the default branch,
# and checks pull requests that change them.
# Regenerate: gardener generate
# Do not edit this workflow directly.
name: "Gardener · Sync tasks"

on:
  push:
    paths:
      - ".gardener/**"
      - ".github/workflows/gardener-*.yml"
  pull_request:
    paths:
      - ".gardener/**"
      - ".github/workflows/gardener-*.yml"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    if: github.event_name == 'pull_request'
    concurrency:
      group: gardener-check-\${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    uses: ${checkRef}

  sync:
    if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    concurrency:
      group: gardener-sync
      cancel-in-progress: false
    permissions:
      contents: read
      id-token: write
    uses: ${syncRef}
    with:
      runtime-url: \${{ vars.GARDENER_RUNTIME_URL }}
`;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

/** GitHub expression string literal. Labels are constrained to a safe character set. */
function yamlSingleQuoted(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function workflowSlug(taskId: string): string {
  return taskId.replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
}

async function readPreviousLock(path: string): Promise<string[]> {
  if (!await exists(path)) return [];
  try {
    const value = JSON.parse(await readFile(path, "utf8")) as { tasks?: Record<string, { workflow?: unknown }> };
    return Object.values(value.tasks ?? {})
      .map((task) => task.workflow)
      .filter((workflow): workflow is string => typeof workflow === "string");
  } catch {
    throw new Error("Existing .gardener/gardener.lock.json is invalid");
  }
}

async function atomicWrite(path: string, content: string): Promise<void> {
  if (await exists(path) && await readFile(path, "utf8") === content) return;
  const temporary = `${path}.tmp-${process.pid}`;
  await writeFile(temporary, content, { encoding: "utf8", mode: 0o644 });
  await rename(temporary, path);
}

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") return false;
    throw error;
  }
}
