import { lstat, mkdir, readFile, readdir, rename, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { canonicalJson } from "@gardener/core";
import { z } from "zod";
import {
  compileGitHubActionsTask,
  GITHUB_ACTIONS_TARGET,
  type GitHubActionsTaskPlanV1,
} from "./actions-target.js";
import { compileTaskSource, type CompiledTask } from "./task-authoring.js";

export const DEFAULT_WORKFLOW_REF =
  "scuffi/gardener-actions/.github/workflows/gardener-issue-task.yml@5821904ec4e4f04f747003940157af74d5b13937";
const GENERATED_MARKER = "# Generated by Gardener. Do not edit.";

const projectSchema = z.strictObject({
  schemaVersion: z.literal("gardener.project/v1"),
  target: z.literal(GITHUB_ACTIONS_TARGET),
  release: z.strictObject({
    workflowRef: z.string().regex(
      /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/\.github\/workflows\/[A-Za-z0-9_.\/-]+\.ya?ml@[0-9a-f]{40}$/,
    ),
  }),
});

interface BuiltTask extends CompiledTask {
  source: string;
  workflow: string;
  actionsPlan: GitHubActionsTaskPlanV1;
}

export interface ProjectBuildResult {
  lockPath: string;
  tasks: Array<{ taskId: string; bundleHash: string; workflow: string }>;
}

const BUG_INTAKE_TASK = `---
schema: gardener.task/v1
id: bug-intake
name: Bug intake
description: Inspects repository conventions and helps issue authors provide actionable bug reports.
trigger:
  event: github.issue.opened
  labels-all:
    - gardener-bug
tools:
  - repository.list_files
  - repository.read_file
effects:
  - issue.comment.create
network:
  default: deny
  allow: []
  deny: []
limits:
  runtime-seconds: 300
  max-turns: 8
  max-tool-calls: 12
  input-tokens: 24000
  output-tokens: 4000
---
Inspect the issue and the repository's relevant conventions.

Propose one concise issue comment containing:

1. The likely affected area.
2. Missing reproduction information.
3. Relevant test locations.
4. A concrete next step for the author or maintainer.

Do not claim that code was changed or that a persistent effect already occurred.
`;

const DOCS_HELPER_TASK = `---
schema: gardener.task/v1
id: docs-helper
name: Documentation helper
description: Locates relevant documentation and suggests a concrete documentation plan.
trigger:
  event: github.issue.opened
  labels-all:
    - gardener-docs
tools:
  - repository.list_files
  - repository.read_file
effects:
  - issue.comment.create
network:
  default: deny
  allow: []
  deny: []
limits:
  runtime-seconds: 300
  max-turns: 8
  max-tool-calls: 12
  input-tokens: 24000
  output-tokens: 4000
---
Inspect the issue and the repository's documentation structure.

Propose one concise issue comment containing:

1. The documentation files most likely involved.
2. Related guidance already present in the repository.
3. Missing information needed from the issue author.
4. A concrete documentation update plan.

Do not claim that documentation was changed or that a persistent effect already occurred.
`;

export async function initializeProject(input: {
  repositoryRoot: string;
  demos: boolean;
}): Promise<{ created: string[]; preserved: string[] }> {
  const root = resolve(input.repositoryRoot);
  const created: string[] = [];
  const preserved: string[] = [];
  const files = new Map<string, string>([
    [".gardener/gardener.json", `${JSON.stringify({
      schemaVersion: "gardener.project/v1",
      target: GITHUB_ACTIONS_TARGET,
      release: { workflowRef: DEFAULT_WORKFLOW_REF },
    }, null, 2)}\n`],
  ]);
  if (input.demos) {
    files.set(".gardener/tasks/bug-intake/TASK.md", BUG_INTAKE_TASK);
    files.set(".gardener/tasks/docs-helper/TASK.md", DOCS_HELPER_TASK);
  }
  for (const [path, content] of files) {
    const target = join(root, path);
    await mkdir(dirname(target), { recursive: true });
    if (await exists(target)) {
      preserved.push(path);
      continue;
    }
    await atomicWrite(target, content);
    created.push(path);
  }
  return { created, preserved };
}

export async function buildProject(input: { repositoryRoot: string }): Promise<ProjectBuildResult> {
  const root = resolve(input.repositoryRoot);
  const gardenerDirectory = join(root, ".gardener");
  const projectPath = join(gardenerDirectory, "gardener.json");
  const project = projectSchema.parse(JSON.parse(await readFile(projectPath, "utf8")));
  const taskRoot = join(gardenerDirectory, "tasks");
  const entries = (await readdir(taskRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name));
  if (entries.length === 0) throw new Error("No .gardener/tasks/*/TASK.md files were found");

  const tasks: BuiltTask[] = [];
  const taskIds = new Set<string>();
  const workflows = new Set<string>();
  for (const entry of entries) {
    const taskPath = join(taskRoot, entry.name, "TASK.md");
    const taskStat = await lstat(taskPath);
    if (!taskStat.isFile() || taskStat.isSymbolicLink()) {
      throw new Error(`${relative(root, taskPath)} is not a regular file`);
    }
    const source = relative(gardenerDirectory, taskPath).replaceAll("\\", "/");
    const compiled = await compileTaskSource(await readFile(taskPath, "utf8"), source);
    if (taskIds.has(compiled.bundle.taskId)) throw new Error(`Duplicate task id: ${compiled.bundle.taskId}`);
    taskIds.add(compiled.bundle.taskId);
    const workflow = `.github/workflows/gardener-${workflowSlug(compiled.bundle.taskId)}.yml`;
    if (workflows.has(workflow)) throw new Error(`Multiple tasks generate ${workflow}`);
    workflows.add(workflow);
    tasks.push({
      ...compiled,
      source,
      workflow,
      actionsPlan: compileGitHubActionsTask(compiled.bundle),
    });
  }
  tasks.sort((left, right) => left.bundle.taskId.localeCompare(right.bundle.taskId));

  const previous = await readPreviousLock(join(gardenerDirectory, "gardener.lock.json"));
  const nextWorkflows = new Set(tasks.map((task) => task.workflow));
  for (const stale of previous.filter((path) => !nextWorkflows.has(path))) {
    const target = join(root, stale);
    if (await exists(target) && (await readFile(target, "utf8")).startsWith(GENERATED_MARKER)) {
      await unlink(target);
    }
  }

  for (const task of tasks) {
    const output = join(root, task.workflow);
    await mkdir(dirname(output), { recursive: true });
    if (await exists(output) && !(await readFile(output, "utf8")).startsWith(GENERATED_MARKER)) {
      throw new Error(`Refusing to overwrite non-Gardener workflow ${task.workflow}`);
    }
    await atomicWrite(output, renderTaskWorkflow(task, project.release.workflowRef));
  }

  const lock = {
    schemaVersion: "gardener.lock/v1",
    target: {
      id: project.target,
      adapterVersion: "1",
      workflowRef: project.release.workflowRef,
    },
    release: project.release,
    tasks: Object.fromEntries(tasks.map((task) => [task.bundle.taskId, {
      source: task.source,
      bundleHash: task.bundleHash,
      workflow: task.workflow,
      bundle: task.bundle,
      deployment: task.actionsPlan,
    }])),
  };
  const lockPath = join(gardenerDirectory, "gardener.lock.json");
  await atomicWrite(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
  return {
    lockPath,
    tasks: tasks.map((task) => ({
      taskId: task.bundle.taskId,
      bundleHash: task.bundleHash,
      workflow: task.workflow,
    })),
  };
}

function renderTaskWorkflow(task: BuiltTask, workflowRef: string): string {
  const labels = task.bundle.triggers[0]?.kind === "github.issue.opened"
    ? task.bundle.triggers[0].labelsAll
    : [];
  const condition = labels.length
    ? labels.map((label) => `contains(github.event.issue.labels.*.name, '${label}')`).join(" && ")
    : "true";
  return `${GENERATED_MARKER}
#
# Source: .gardener/${task.source}
# Task: ${task.bundle.taskId}
# Bundle: sha256:${task.bundleHash}
# Regenerate: gardener build
# Do not edit this workflow directly.
name: ${yamlString(`Gardener · ${task.bundle.name}`)}

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  gardener:
    if: \${{ ${condition} }}
    permissions:
      contents: ${task.actionsPlan.planningPermissions.contents}
      issues: ${task.actionsPlan.effectsPermissions.issues}
      id-token: ${task.actionsPlan.planningPermissions.idToken}
    uses: ${workflowRef}
    with:
      harness-url: \${{ vars.GARDENER_INGRESS_URL }}
      task-id: ${yamlString(task.bundle.taskId)}
      task-name: ${yamlString(task.bundle.name)}
      task-source: ${yamlString(`.gardener/${task.source}`)}
      task-bundle-hash: ${task.bundleHash}
`;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function workflowSlug(taskId: string): string {
  return taskId.replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
}

async function readPreviousLock(path: string): Promise<string[]> {
  if (!await exists(path)) return [];
  try {
    const value = JSON.parse(await readFile(path, "utf8")) as { tasks?: Record<string, { workflow?: unknown }> };
    return Object.values(value.tasks ?? {})
      .map((task) => task.workflow)
      .filter((workflow): workflow is string => typeof workflow === "string");
  } catch {
    throw new Error("Existing .gardener/gardener.lock.json is invalid");
  }
}

async function atomicWrite(path: string, content: string): Promise<void> {
  const temporary = `${path}.tmp-${process.pid}`;
  await writeFile(temporary, content, { encoding: "utf8", mode: 0o644 });
  await rename(temporary, path);
}

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") return false;
    throw error;
  }
}

export function canonicalProjectLock(value: unknown): string {
  return canonicalJson(value);
}
