import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  canonicalJson,
  canonicalSha256,
  compileAgentRevision,
  createAgentSource,
  parseAgentSource,
} from "../packages/core/src/index";
import type { AgentProvenanceV1 } from "../packages/contracts/src/index";

const root = resolve(import.meta.dirname, "..");
const output = resolve(root, "apps/gardener/migrations/0009_starter_agents.sql");
const publishedAt = "2026-09-16T00:00:00.000Z";
const publisher = {
  provider: "gardener" as const,
  principal: { kind: "system" as const, id: "system:starter-agents", displayName: "Gardener" },
};
const provenance: AgentProvenanceV1 = {
  source: "migration",
  authoredBy: publisher,
  publishedBy: publisher,
  authoredAt: publishedAt,
  publishedAt,
};
const versions = {
  compilerVersion: "gardener-agent-compiler/1",
  capabilityCatalogVersion: "gardener-capabilities/1",
  runtimeVersion: "gardener-agent-runtime/1",
};

const starters = [
  {
    key: "issue_triage",
    slug: "gardener-starter-issue-triage",
    path: "examples/agents/issue-triage/AGENT.md",
  },
  {
    key: "bug_intake",
    slug: "gardener-starter-bug-intake",
    path: "examples/agents/bug-intake/AGENT.md",
  },
  {
    key: "documentation_helper",
    slug: "gardener-starter-documentation-helper",
    path: "examples/agents/documentation-helper/AGENT.md",
  },
] as const;

const sql: string[] = [
  "-- Generated by scripts/generate-starter-agents.ts. Do not edit by hand.",
  "-- Published and activated revisions remain unable to run until an owner creates and enables", 
  "-- an explicit repository assignment. Seed installation never grants repository authority.",
  "",
];

for (const starter of starters) {
  const agentId = `agent_gardener_starter_${starter.key}`;
  const revisionId = `revision_gardener_starter_${starter.key}_v1`;
  const sourceText = await readFile(resolve(root, starter.path), "utf8");
  const source = createAgentSource(sourceText);
  const spec = parseAgentSource(source);
  const built = await compileAgentRevision(source, {
    agentId,
    revision: 1,
    revisionId,
    provenance,
    ...versions,
    now: () => new Date(publishedAt),
  });
  const parsedHash = await canonicalSha256(built.revision.spec);
  const compiledHash = await canonicalSha256(built.compiled);
  const provenanceHash = await canonicalSha256(provenance);

  sql.push(
    `INSERT OR IGNORE INTO agents (id, slug, name, description, enabled, revision_counter, created_by, created_at, updated_at) VALUES (${q(agentId)}, ${q(starter.slug)}, ${q(spec.name)}, ${q(spec.description)}, 0, 1, 'system:starter-agents', ${q(publishedAt)}, ${q(publishedAt)});`,
    `INSERT OR IGNORE INTO agent_revisions (id, agent_id, revision, source_md, source_hash, parsed_json, parsed_hash, compiled_json, compiled_hash, provenance_json, provenance_hash, compiler_version, catalog_version, runtime_version, published_paused, published_by, published_at) SELECT ${q(revisionId)}, ${q(agentId)}, 1, ${q(canonicalJson(source))}, ${q(built.revision.sourceHash)}, ${q(canonicalJson(built.revision.spec))}, ${q(parsedHash)}, ${q(canonicalJson(built.compiled))}, ${q(compiledHash)}, ${q(canonicalJson(provenance))}, ${q(provenanceHash)}, ${q(versions.compilerVersion)}, ${q(versions.capabilityCatalogVersion)}, ${q(versions.runtimeVersion)}, 1, 'system:starter-agents', ${q(publishedAt)} WHERE EXISTS (SELECT 1 FROM agents WHERE id = ${q(agentId)} AND slug = ${q(starter.slug)});`,
    `INSERT OR IGNORE INTO agent_activations (agent_id, revision_id, activated_by, activated_at) SELECT ${q(agentId)}, ${q(revisionId)}, 'system:starter-agents', ${q(publishedAt)} WHERE EXISTS (SELECT 1 FROM agent_revisions WHERE id = ${q(revisionId)} AND agent_id = ${q(agentId)});`,
    `INSERT OR IGNORE INTO agent_activation_history (id, agent_id, previous_revision_id, revision_id, action, actor_id, reason, created_at) SELECT ${q(`activation_gardener_starter_${starter.key}_v1`)}, ${q(agentId)}, NULL, ${q(revisionId)}, 'activate', 'system:starter-agents', 'Installed as a safe unassigned starter Agent', ${q(publishedAt)} WHERE EXISTS (SELECT 1 FROM agent_activations WHERE agent_id = ${q(agentId)} AND revision_id = ${q(revisionId)});`,
    "",
  );
}

sql.push(
  "UPDATE gardener_schema SET version = 9 WHERE singleton = 1 AND version = 8;",
  "",
);

const generated = sql.join("\n");
if (process.argv.includes("--check")) {
  const current = await readFile(output, "utf8").catch(() => "");
  if (current !== generated) {
    console.error("Starter Agent migration is stale. Run: pnpm generate:starter-agents");
    process.exitCode = 1;
  }
} else {
  await writeFile(output, generated, { mode: 0o644 });
  console.log(`Generated ${output}`);
}

function q(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}
